#docker-compose up
version: "3.7"

networks:
  shared-network:
    driver: bridge

services:
  db:
    container_name: sales_db
    networks:
      - shared-network
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: 1234
    ports:
      - 5434:5434